### ISSUE TITLE
add cutefish interface to mocaccinoOS

### ISSUE THREAD

**Issue by telmo1241** [mocaccinoOS/desktop#110]
For now it's not a priority, but I would like you to add this interface that is still in beta to mocaccinoOS

All the code is here:https://github.com/cutefishos

**Comment by joostruis** [comment]
We currently follow Gentoo stable tree on MOS desktop. I don't expect this to be in there for some time.

**Comment by telmo1241** [comment]
this means that if it is added to gentoo it can be added to mocaccinoOS does this mean that if it is added to gentoo it can be added to mocaccinoOS?

**Comment by telmo1241** [comment]
@joostruis ?

**Comment by telmo1241** [comment]
after some time the doubt still persists

**Comment by sebaro** [comment]
There is an overlay here:
https://github.com/HougeLangley/cutefishos-overlay

**Comment by telmo1241** [comment]
@joostruis
