### ISSUE TITLE
GDM shows MOTD

### ISSUE THREAD

**Issue by joostruis** [mocaccinoOS/desktop#125]
When you enter your password and hit enter GDM shows a disrupted ASCII image that appears to be the content of /etc/motd
This looks very buggy and shouldn't happen.

**Comment by joostruis** [comment]
`sed --in-place '/motd/d' /etc/pam.d/system-login && echo "session    optional     pam_motd.so motd=/etc/motd" >> /etc/pam.d/sshd`

Optional solution: remove the module from /etc/pam.d/system-login  and add it to /etc/pam.d/sshd.
This way the problem is solved in GDM and the motd is only shown if you ssh into the system. (sadly not in tty1)

**Comment by msdobrescu** [comment]
So far, an workaround is to style the GDM in a way to have a limited size or 0. That won't remove the delay introduced by the fact that there is a message that awaits to be read.

**Comment by msdobrescu** [comment]
A solution would be to remove completely the PAM MOTD plugin from system-login and add the motd content to a script in `/etc/profile.d/`:

```
echo '[2m'
echo '        ..'
echo '      ..  ..'
echo '            ..'
echo '             ..'
echo '            ..'
echo '           ..'
echo '         ..'
echo '##       ..    ####'
echo '##.............##  ##'
echo '##.............##   ##'
echo '##.............## ##'
echo '##.............###'
echo ' ##...........##'
echo '  #############'
echo '  #############'
echo '#################'
echo ''
echo '[22mWelcome to [33mMocaccinoOS'
```

**Comment by joostruis** [comment]
This is solved now.
