### ISSUE TITLE
Lightdm autologin doesn't work

### ISSUE THREAD

**Issue by joostruis** [mocaccinoOS/desktop#126]
On live session lightdm should autologin the user but it doesn't work.
Lightdm is used on the MATE iso.

**Comment by msdobrescu** [comment]
In my tests, it log in automatically if the session matches in /etc/lightdm/lightdm.conf:

`autologin-session=mate`

Possibly, if the fixup_gnome_autologin_session function call is not done for LightDM, it may run also, but I did not try yet.
