### ISSUE TITLE
Installer should cleanup properly

### ISSUE THREAD

**Issue by joostruis** [mocaccinoOS/desktop#128]
- After installation the installer icon is still present on the desktop.
- After installation mocaccino/live-setup is still installed.  /etc/yip.d/live triggers /usr/bin/live.sh to run each boot. As a result it performs all kinds of actions on the installed PC that should not happen. 
as an example it floods /etc/gdm/custom.conf with : 
AutomaticLoginEnable=true
AutomaticLogin=mocaccino
TimedLoginEnable=true
TimedLogin=mocaccino
TimedLoginDelay=0

**Comment by msdobrescu** [comment]
Similarly for KDE iso.
/etc/sddm.conf contains:

```
[Autologin]
Session=plasma
```
The system autologins as root, then remains in a black screen.

**Comment by msdobrescu** [comment]
Tested on a KDE iso. Calamares can run with -d. The following log was generated by issuing in console:

`calamares-pkexec -d > /home/mocaccino/calamares.log`

[calamares.log](https://github.com/mocaccinoOS/desktop/files/6795802/calamares.log)

**Comment by joostruis** [comment]
It seems we still have this issue with at least GNOME iso.

**Comment by joostruis** [comment]
Solved by this commit https://github.com/mocaccinoOS/os-commons/commit/8b452209210edb9f6e883525fd9760bfba90c175
