### ISSUE TITLE
Missing translated languages ​​on all interfaces

### ISSUE THREAD

**Issue by telmobss1** [mocaccinoOS/desktop#133]
All interfaces are missing translations

**Comment by joostruis** [comment]
What translations should be made available?

**Comment by telmo1241** [comment]
all updates that are available to be used on the respective interfaces


Especially select the language through calamares

I speak Portuguese from Portugal and Esperanto

**Comment by telmo1241** [comment]
just a quick mention, in KDE plasma there is no translated language
