### ISSUE TITLE
zfs use flag inconsistency 

### ISSUE THREAD

**Issue by welele08** [mocaccinoOS/desktop#15]
In  [01-base.use](https://github.com/mocaccinoOS/desktop/blob/master/packages/layers/system-x/package.use/01-base.use), "kernel-builtin" use flag is enable for sys-fs/zfs. These use flag is masked in current portage profile (in default/linux in fact).

At the moment, this use flag is disabled and installation of sys-fs/zfs trigger sys-fs/zfs-kmod.

Suggestion : 

- drop those use flag in system-x and build upon zfs-kmod
or
- if zfs is in mocaccinoos kernel's, unmask the "kernel-builtin" use flag with /etc/portage/profile/use.mask

Not sure what is the best.

**Comment by mudler** [comment]
@welele08 thanks for noticing, and you are right.

To unblock ourselves it's better to handle  #5 and #6 first, so we can carefully pick which useflag goes in each layer without bumping the base one. Marking it as blocked for now until those are solved

**Comment by mudler** [comment]
@joostruis can we close this I guess, right?
