### ISSUE TITLE
apps/firefox retains the Gentoo configuration

### ISSUE THREAD

**Issue by RafaelPalomar** [mocaccinoOS/desktop#155]
`apps/firefox` has the Gentoo configuration for toolbar, bookmarks and welcome page. This could be tailored to MocaccinoOS by deploying a new `distribution.ini` file that overrides the one provided by Gentoo.

**Comment by joostruis** [comment]
Feel free to borrow upstream ini file and make the changes to it.
https://github.com/gentoo/gentoo/blob/master/www-client/firefox/files/distribution.ini
