### ISSUE TITLE
missing boltctl (thunderbolt compatibility)

### ISSUE THREAD

**Issue by jcfrosty** [mocaccinoOS/desktop#159]
without boltctl Mocaccino has no thunderbolt compat. Gnome has a Thunderbolt control panel, but it recognizes no thunderbolt devices for user auth/approval because boltctl doesn't exist.

**Comment by joostruis** [comment]
You are basically requesting sys-apps/bolt

**Comment by jcfrosty** [comment]
effectively yes. Its what gives us thunderbolt support since thunderbolt has stringent security by default in most systems. Strangely, I don't know why gnome would have a "thunderbolt" settings pane (under settings > privacy) if you don't have thunderbolt support or boltctl, but its there. For me, it claims either the system lacks thunderbolt support or it has been disabled in bios. Neither of which are true, I have TB3 on my system, It just cannot tell because its uses boltctl to communicate with the TB controller.
