### ISSUE TITLE
Add layers for packages commented in the gnome spec file

### ISSUE THREAD

**Issue by mudler** [mocaccinoOS/desktop#16]
While porting layers from portage-tree, few packages have been missed. I've temporarly disabled them in the ISO creation.

We need to package (at least) the ones that are commented here: 

https://github.com/mocaccinoOS/ci/blob/master/specs/gnome.yaml#L4

**Comment by joostruis** [comment]
www-client/epiphany isn't really needed.
How do you want to go ahead with this?

**Comment by joostruis** [comment]
Here is my first take on this issue:

https://github.com/mocaccinoOS/desktop/compare/f96229c63e7c...333acd45599a

**Comment by mudler** [comment]
Part of this changeset: https://github.com/mocaccinoOS/desktop/commit/9ecf957bbb28e7231072057fdb7b9d3e7b5779ec

**Comment by joostruis** [comment]
This issue can be closed. If not feel free to reopen.
