### ISSUE TITLE
nvidia-drivers-lts missing dependency

### ISSUE THREAD

**Issue by jcfrosty** [mocaccinoOS/desktop#182]
attempting to launch nvidia-settings results in Error while loading shared library: **libjansson.so.4** : cannot open shared object file: no such file or directory.

Needs package:
dev-libs/jansson

**Comment by joostruis** [comment]
dev-libs/jansson should be added to layers/X

**Comment by msdobrescu** [comment]
In my tests on a stable install, it works fine now.
