### ISSUE TITLE
Virtualbox-guest-additions not usable for iso

### ISSUE THREAD

**Issue by welele08** [mocaccinoOS/desktop#215]
VirtualBox (and other kernel modules) can't be used in iso at the moment. It's related to the `depmod -a`  [here](https://github.com/mocaccinoOS/desktop/blob/b58f28b7811c15db92e48623bad54124e366fc98/packages/kernel-modules/kernel-modules/finalize.yaml#L2)

Indeed, `luet makeiso` will run finalizer, and the `depmod -a ` command for the running kernel. In fact, for the kernel of the machine building the iso, and not the kernel installed in the iso.

Suggestion : force the version with something like this `depmod -a ${KERVER}` or relying on `eselect` (which might be more durable ?)

**Comment by geaaru** [comment]
With new luet versions the envs where finalizer are executed aren't with the all envs available in the shell where luet is running.

So, the better way is something like this (https://github.com/mocaccinoOS/kernel-repo/blob/master/packages/kernels/mocaccino-lts/finalize.yaml#L2) where the version could be a label in definition.yaml:
```
labels:
    lts_kernel_version: "5.10.60"
```

and then on finalizer something like this:
```
- depmod -a {{ ( index .Vales.labels "lts_kernel_version" ) }}
```
```

**Comment by welele08** [comment]
Yep. But in this case the "its_kernel_version" label as to be modified any time there is a version bump in kernel-repo. 
Does autobump script can handle those label ? (I think in term of long term maintenance. Avoiding human manipulation that can be forgotten seems essential to me.)
