### ISSUE TITLE
Split base useflag set

### ISSUE THREAD

**Issue by mudler** [mocaccinoOS/desktop#5]
https://github.com/mocaccinoOS/desktop/blob/master/packages/layers/X/package.use/02-Sabayon.use

Contains all the useflags from Sabayon. 

They shouldn't be applied at the beginning. Instead we should have only one useflags set which is tightly coupled with which is installed in that stage.

The other layers then, will ship their own use flag set, depending on the packages that needs to be installed.

Blocked by #6 
- [x] [layers/X](https://github.com/mocaccinoOS/desktop/tree/master/packages/layers/X)
- [x] [apps/calamares](https://github.com/mocaccinoOS/desktop/tree/master/packages/layers/calamares)
- [x] [layers/gnome-common](https://github.com/mocaccinoOS/desktop/tree/master/packages/layers/gnome-common)
- [x] [layers/gnome](https://github.com/mocaccinoOS/desktop/tree/master/packages/layers/gnome)
- [x] [layers/kde-apps-minimal](https://github.com/mocaccinoOS/desktop/tree/master/packages/layers/kde-apps-minimal)
- [x] [layers/mate](https://github.com/mocaccinoOS/desktop/tree/master/packages/layers/mate)
- [x] [layers/plasma](https://github.com/mocaccinoOS/desktop/tree/master/packages/layers/plasma)
- [x] [layers/qt](https://github.com/mocaccinoOS/desktop/tree/master/packages/layers/qt)
- [x] [layers/sys-fs](https://github.com/mocaccinoOS/desktop/tree/master/packages/layers/sys-fs)
- [x] [layers/sys-tools](https://github.com/mocaccinoOS/desktop/tree/master/packages/layers/sys-tools)
- [x] [layers/system-x](https://github.com/mocaccinoOS/desktop/tree/master/packages/layers/system-x)

**Comment by joostruis** [comment]
I agree. Didn't know it was possible to add use flags per layer, but makes sense.

**Comment by geaaru** [comment]
This could be done only for some packages that aren't libs or packages used by different atoms.
Instead, where there are libs used by different layers it's better to have a package like `mocaccino-overlay-x` that is common.
This avoids rebuilding packages for errors.

I think that for some packages without reverse deps we could set use-flags directly on the package probably.

Please, take care of the number of the use of flags files. FWIS the use-flags with a bigger number are applied at the end and they are used at the end. I did the same error in portage-tree too.

Probably we need to use a range 1-50 for Mocaccino OS and to leave >50 for users override.

**Comment by mudler** [comment]
That's not true. We should group common libs as much as we can. Let's do baby steps :)

**Comment by mudler** [comment]
blocked by #6

**Comment by joostruis** [comment]
At the moment 02-Sabayon.use lives in layers/X
If correct at this moment we have nothing installed that is in this list. I moved all relevant atoms to the layers where they are installed. So what now? We keep it around? If we do, this means that ALL use flags are set for layers that depend on X. So if in the future we add an atom from this list the use flags will be applied.

**Comment by joostruis** [comment]
Closing. Keeping 02-Sabayon.use around for now.
