### ISSUE TITLE
Virtualbox doesn't work 

### ISSUE THREAD

**Issue by joostruis** [mocaccinoOS/desktop#71]
After some attempts I still am unable to use Virtualbox.

![vbox](https://user-images.githubusercontent.com/1949179/117586786-99a62280-b11a-11eb-99ce-7926b89c6386.png)

**Comment by telmo1241** [comment]
I also got the same problem, even though the modules were

**Comment by joostruis** [comment]
https://github.com/mocaccinoOS/desktop/commit/11fa6db4f5c8b1d74caad83d210182cb96c81737
