### ISSUE TITLE
Screen recorder can't record screen 

### ISSUE THREAD

**Issue by telmo1241** [mocaccinoOS/desktop#75]
The screen recorders do not work on mocaccinoOS as well as their extensions 

In addition, gs connect also does not work

**Comment by joostruis** [comment]
Can you please provide a bit more info?
There is nothing on this report I can work with.

**Comment by joostruis** [comment]
Closing this.

**Comment by telmo1241** [comment]
@joos
![20210703_202344](https://user-images.githubusercontent.com/80489312/124364931-b81d2b80-dc3c-11eb-89de-1b9f5935332a.jpg)
truis 

Reabrindo o problema

![20210703_202347](https://user-images.githubusercontent.com/80489312/124364928-b18eb400-dc3c-11eb-9612-eaf6a6032cb6.jpg)
