### ISSUE TITLE
Application store for mocaccinoOS 

### ISSUE THREAD

**Issue by telmo1241** [mocaccinoOS/desktop#79]
Some people came into the newly created group Portuguese to ask about discover and gnome software 

Are these software being adapted to work with luet or are you building a new interface for luet?

**Comment by joostruis** [comment]
Discover and gnome software have nothing to do with Luet. If you are asking if we are going to make Discover and gnome software available so it can be used with flatpak, then the answer would be yes.

**Comment by telmo1241** [comment]
I wondered if Gnome software and Discover would also be able to use luet
