### ISSUE TITLE
Adapt themes evenly to all or most interfaces 

### ISSUE THREAD

**Issue by telmo1241** [mocaccinoOS/desktop#81]
I've seen the ISO dev of mocaccinoOS, but did not like the themes much compared to the standard 

Could you know if you are interested in adapting the themes for both plasma kde and gnome and other interfaces (as far as possible) more at least consistently?

**Comment by joostruis** [comment]
Not for the moment. We lack money and people to do that.

**Comment by telmo1241** [comment]
Thank you, when mocaccinoOS is ready you may ask again about the Themes
